apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-argocd-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/niyaz-hasan/cicd-Argocd-manifests-repo.git
    targetRevision: main
    path: python-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true



